name: "Accessibility Analysis"
description: "Analyze the accessibility of a website"

inputs:
  config:
    description: "Configuration file path"

  token:
    description: "Project token"
  organization:
    description: "Organization name"
  project:
    description: "Project name"

  commit:
    description: "Commit hash"
  branch:
    description: "Branch name"
  target:
    description: "Target branch"
  pull_request:
    description: "Pull request number"
  contributor_name:
    description: "Contributor name"
  contributor_email:
    description: "Contributor email"

  retention:
    description: "Retention period"
  scope:
    description: "Analysis scope"
  assignee_email:
    description: "Assignee email"
  framework:
    description: "Test ramework"

  path:
    description: "Path to the report folder"
  concurrency:
    description: "Artifact upload concurrency"

  server:
    description: "Server url"
  timeout:
    description: "Timeout"
  dry_run:
    description: "Dry run mode"

outputs:
  score:
    description: "Accessibility score"

runs:
  using: "node20"
  main: "dist/index.js"
