name: "Accessibility Analysis"
description: "Analyze the accessibility of a website"
branding:
  icon: check
  color: green

inputs:
  config:
    description: "Configuration file path"

  token:
    description: "Project token"
  organization:
    description: "Organization name"
  project:
    description: "Project name"

  commit_hash:
    description: "Commit hash"
  commit_message:
    description: "Commit message"
  branch:
    description: "Branch name"
  target_branch:
    description: "Target branch"
  pull_request:
    description: "Pull request number"
  contributor_name:
    description: "Contributor name"
  contributor_email:
    description: "Contributor email"

  retention:
    description: "Retention period"
  scope:
    description: "Analysis scope"
  assignee_email:
    description: "Assignee email"

  report_paths:
    description: "Paths to report folders"
  concurrency:
    description: "Artifact upload concurrency"

  server:
    description: "Server url"
  timeout:
    description: "Timeout"
  dry_run:
    description: "Dry run mode"

outputs:
  score:
    description: "Accessibility score"

runs:
  using: "node20"
  main: "dist/index.js"
